[package]
name = "adxl345"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = { version = "1.0.0"}
embedded-hal-async = { version = "1.0.0"}
accelerometer = {version = "^0.12.0"}
bitflags = "2.5.0"

[features]
default = ["i16x3", "spi"]
i16x3 = []
u16x3 = []
i2c = []
spi = []